### PR TITLE
x11-misc/barrier add qt-network dependancy

### PR DESCRIPTION
**Pull request by soubiliz**
Signed-off-by: Jules de Sartiges <desartij@protonmail.com>

### CODE REVIEW

**Comment by jfmcarreira** [comment]
Your email is not correct!

**Comment by soubiliz** [comment]
Sorry. should be okay now

**Comment by soubiliz** [comment]
is there anything still missing?

**Comment by jfmcarreira** [comment]
It's done. There is only some issues to push to gentoo server, due to the signature policy. But it is on older commits.

Thanks for the contribution.

**Pull request closed without merging**
